### PR TITLE
Make install script more flexible and future-proof

### PR DESCRIPTION
**Pull request by ebastos**
As per #54 this will provide the necessary framework.
It does uses bash syntax, but this should be a non-issue in most modern *nix systems

### CODE REVIEW

**Comment by adiclepcea** [comment]
:+1: 
Nice. Now that I see this improvement, I think that we should also do something similar for Windows (good or bad, it is a go supported platform). 
And as an idea, we could also do an installer that could install ergo as a service (perhaps for systemd would suffice).

**Comment by cristianoliveira** [comment]
> Nice. Now that I see this improvement, I think that we should also do something similar for Windows (good or bad, it is a go supported platform).

Would be great! I have no idea how to do it though 😅 

> And as an idea, we could also do an installer that could install ergo as a service (perhaps for systemd would suffice).

Sure. Now that we have the command `add` it's possible to have ergo running as a service. I think we may need the command `delete`/`remove` also

**Comment by adiclepcea** [comment]
For windows I can give it a try with the installer.
For the service side, this would be a great addition. The benefits are obvious. I believe we should take it in steps. First add the ```delete``` / ```remove``` command, possible even a ```replace``` / ```modify```, and then add services for linux, osx, freebsd and windows separately. Each one is different. 
For Linux systemd would be perhaps the most used system, so perhaps the best choice, but care must be taken since the system might be using the old init.d system. 
For osx, I'l leave it to someone else to express any opinion 😄 
For FreeBSD I'll take a shot if we decide to go forward with this.
For Windows ... idem.

**Comment by cristianoliveira** [comment]
@adiclepcea Feel free to go for the freebsd! :)

**Pull request merged**
