### PR TITLE
Add fmt vet lint

### LINKED ISSUE #47: Improve code quality
By this I mean adding compliance checking with the go coding standards ( gofmt, go vet and golint).

### PR DESCRIPTION
**Pull request by adiclepcea**
This adds fmt, vet and lint checks for all the tests.
This will make sure that no code that does not respect the Golang
recomended code style will be submited.
This should close #47

### CODE REVIEW

**Comment by cristianoliveira** [comment]
Apparently, the integration tests now need admin grants for running and Appveyor doesn't run with this grants. That why its failing. We have 2 options, discover how to run it as admin in Appveyor or skip this tests on CI and leave then as extra tests.

**Comment by cristianoliveira** [comment]
I will try to figure out how to run with those grants, but for now, I think we may need to skip them.

**Comment by cristianoliveira** [comment]
Fixed the tests :)

**Comment by adiclepcea** [comment]
:+1:

**Pull request merged**
