### PR TITLE
Golint fixes

### LINKED ISSUE #20: Style: Fix lints reports
Today we have 30% for go lint on goreport. We can do better.

https://goreportcard.com/report/github.com/cristianoliveira/ergo

```
Golint is a linter for Go source code.

        ergo/commands/setup.go
        Line 12: warning: exported function Setup should have comment or be unexported (golint)
        Line 14: warning: don't use underscores in Go names; var proxy_url should be proxyURL (golint)

        ergo/proxy/config.go
        Line 10: warning: exported type Service should have comment or be unexported (golint)
        Line 15: warning: exported type Config should have comment or be unexported (golint)
        Line 23: warning: exported method Config.GetService should have comment or be unexported (golint)
        Line 35: warning: exported function NewConfig should have comment or be unexported (golint)
        Line 44: warning: exported function LoadServices should have comment or be unexported (golint)

        ergo/commands/url.go
        Line 8: warning: exported function Url should have comment or be unexported (golint)

        ergo/proxy/proxy.go
        Line 37: warning: exported function NewErgoProxy should have comment or be unexported (golint)
        Line 78: warning: exported function ServeProxy should have comment or be unexported (golint)

        ergo/main.go
        Line 11: warning: exported var VERSION should have comment or be unexported (golint)
        Line 13: warning: exported const USAGE should have comment or be unexported (golint)

        ergo/tests/ergo_run_test.go
        Line 22: warning: don't use underscores in Go names; var apps_outoput should be appsOutoput (golint)
        Line 47: warning: don't use underscores in Go names; var apps_outoput should be appsOutoput (golint)
        Line 72: warning: don't use underscores in Go names; var apps_output should be appsOutput (golint)

        ergo/commands/list.go
        Line 8: warning: exported function List should have comment or be unexported (golint)

        ergo/commands/list_names.go
        Line 8: warning: exported function ListNames should have comment or be unexported (golint)

        ergo/commands/run.go
        Line 9: warning: exported function Run should have comment or be unexported (golint)
```

### PR DESCRIPTION
**Pull request by srini156**
- Fixes for go vet
- Fixes for golint (in progress)
- Fixes #20

### CODE REVIEW

**Comment by cristianoliveira** [comment]
Hey @srini156 codewise it seems ok but that the tests aren't passing. Could you take a look on that?

```
make test
# github.com/cristianoliveira/ergo/proxy
../../go/src/github.com/cristianoliveira/ergo/proxy/proxy.go:98:47: s.Url undefined (type Service has no field or method Url, but does have URL)
# _/Users/cristianoliveira/other/ergo/proxy
proxy/proxy.go:98:47: s.Url undefined (type Service has no field or method Url, but does have URL)
make: *** [test] Error 2
```

**Comment by srini156** [comment]
@cristianoliveira - That is because of the imports.
```
-       "github.com/cristianoliveira/ergo/proxy"
+       "../proxy"

**Comment by srini156** [comment]
-       "github.com/cristianoliveira/ergo/proxy"
+       "../proxy"```

**Comment by cristianoliveira** [comment]
I am not sure if it that the cause. You have upper-cased the var name inside the struct `service.URL` but you didn't changed on all occurrences to the new name. For instance:

https://github.com/srini156/ergo/blob/c76d79670d2703ce1d84186f5fc79e9c946dbce2/commands/list.go#L15

https://github.com/srini156/ergo/blob/c76d79670d2703ce1d84186f5fc79e9c946dbce2/commands/list_names.go#L14

Rebasing your change with the last master will shows up some other occurrences.

**Comment by srini156** [comment]
Yes, that is not failing local build because of the import to your GitHub project which has `Url` and not `URL` (that is due to the import). 
Ref -
 https://github.com/srini156/ergo/blob/c76d79670d2703ce1d84186f5fc79e9c946dbce2/commands/list_names.go#L5

**Comment by cristianoliveira** [comment]
Looks great! I going to fix the other error after merging :)

**Comment by cristianoliveira** [comment]
Thanks for your contributions :)

**Comment by srini156** [comment]
Thanks a lot for your continued patience with me. I am really sorry that I couldn't help end to end. @cristianoliveira. I will definitely try out `ergo` and see if I can contribute further.

**Pull request merged**
